### ISSUE TITLE
${packaging.type} variable in pom.xml breaks Ivy

### ISSUE THREAD

**Issue by maltem-za** [jax-rs/api#572] opened 2017-10-04 12:27 UTC
The ${packaging.type} variable introduced in 71c20bd breaks Ivy with the following output:

```
:: problems summary ::
:::: WARNINGS
		[NOT FOUND  ] javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type} (491ms)

	==== public: tried

	  https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type}

		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}

		::::::::::::::::::::::::::::::::::::::::::::::
```

Judging by the todo comment in pom.xml you are aware of the issue, but perhaps you are not aware that, in its current state, this still breaks Ivy. It also breaks the download link on mvnrepository.com, by the way.

Here is the same issue in a different project with some interesting comments: https://github.com/ronmamo/reflections/issues/169

I can resolve the issue manually by putting the jar files into my Ivy cache directory. As I'm using IntelliJ IDEA and the IvyIDEA plugin I can't use the system property fix mentioned in the link above (or can't figure out how). Maybe there is a better way to resolve this with Ivy, but I'm not sure as I'm quite new to it.

**Comment by ChristianCiach** [comment] 2017-10-04 13:55
Duplicate of #571

**Comment by maltem-za** [comment] 2017-10-04 14:05
@ChristianCiach Ah, thanks, I didn't find that one (obviously).

**Comment by maltem-za** [comment] 2017-10-16 09:04
For anyone else who comes across this, you can fix it for Ivy by adding a filesystem resolver like this:

```
	   <filesystem name="mylocal">
	      <ivy pattern= "${ivy.default.ivy.user.dir}/local/[organisation]/[module]/[type]s/[artifact]-[revision].[ext]" />
	      <artifact pattern= "${ivy.default.ivy.user.dir}/local/[organisation]/[module]/[type]s/[artifact]-[revision].[ext]" />
	   </filesystem>
```

Then all you have to do is place the jar file in the configured location, for example:
`~/ivy2/local/javax.ws.rs/javax.ws.rs-api/jars/javax.ws.rs-api-2.1.jar`

Thanks to @mpetris for the solution.

**Comment by Randgalt** [comment] 2017-10-25 21:01
This really needs to be fixed ASAP. It breaks sbt as well. I don't understand the need for `<packaging>${packaging.type}</packaging>` in the pom anyway. Why not just make it JAR?

**Comment by pavelbucek** [comment] 2017-10-25 22:58
closing as duplicate of https://github.com/jax-rs/api/issues/571

**Closed by pavelbucek** 2017-10-25 22:58 UTC

**Comment by Randgalt** [comment] 2017-10-25 23:01
Sad that you've closed this @pavelbucek - #571 does not fix the problem.

**Comment by nicktrav** [comment] 2017-10-31 01:34
This is breaking things in the Pants build tool, which under the hood uses Ivy. I also don't understand why this issue was closed along with #571.

Seems like a trivial fix to just make this `<packaging>jar</packaging>`?

**Comment by Randgalt** [comment] 2017-10-31 01:50
@nicktrav see https://github.com/jax-rs/api/pull/576

**Comment by nicktrav** [comment] 2017-10-31 01:59
I'm very much in support. Left (non-passive-aggressive) my 👍 .
